# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170620_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ManyToManyField(null=True, related_name='recipient', to='chat.User', verbose_name='list of recipients'),
        ),
    ]
