# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170625_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ManyToManyField(blank=True, related_name='recipient', to='chat.User', verbose_name='list of recipients'),
        ),
    ]
